### ISSUE TITLE
It seems python 3.6.x is required.

### ISSUE THREAD

**Issue by stuffinator** [thomasa88/pyets2_telemetry#1]
Hi, I had a problem getting this thing to work. I would download it, put it in the plugins folder (which I had to create separately), started the game, but got no popup with "Request to use advanced SDK features detected".

Upon inspecting "~/.local/share/Euro Truck Simulator 2/game.log.txt" I found two lines stating

> 00:00:05.644 : loading 'pyets2_telemetry_loader_1_0' '/drives/programs/steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64/plugins/pyets2_telemetry_loader_1_0.so'
00:00:05.644 : <ERROR> unable to load: 'libpython3.6m.so.1.0: cannot open shared object file: No such file or directory'

I only had Python 3.7.4 installed, but after also installing 3.6.0 it finally worked. So yeah, it seems 3.6.x is required for the plugin to work.

So this is not really an issue, but I thought it's worth mentioning in case others run in to the same problem.

Thanks btw. for making a linux equivalent of the ets2 telemetry stuff, I really appreciate it.

**Comment by Luzifer** [comment]
I've opened a pull-request for Python 3.7-support and could provide you with a compiled version built against Python 3.7.4 if you need one (but will not attach it to the PR or the issue as I'm not the original author).

**Comment by stuffinator** [comment]
My bad, I didn't close the issue. It runs fine with 3.6.0 and I just wanted to let others know in case they run into problems.

**Comment by Draecal** [comment]
Please update it, I use **Debian 10** and python3.6 was **deprecated** so there is no way I can get **libpython3.6m.so.1.0** installed
